name = "JuliaKitchenSink"
uuid = "e794a6cc-0a6f-11ea-309f-53a2f22cc92d"
authors = ["Daryoush Mehrtash <dmehrtash@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
